language:          node_js
node_js:
  - 10
cache:
  npm:             true
  directories:
    - ~/.cache
dist:              trusty
sudo:              required
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli
script:
  - npm run build -- --prod
  - npm run coverage
  - npm run lint
  - npm run e2e
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run compodoc:coverage; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then npm run codacy-coverage; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then npm run ghpages; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then npm pack; fi'
before_deploy:
  - npm install @angular/cli
deploy:
  - provider:      pages
    skip_cleanup:  true
    github_token:  "$GITHUB_TOKEN"
    local_dir:     dist/apps/widgets-system/
    fqdn:          ui.gorilainvest.com.br
    keep-history:  true
    on:
      branch:      master
      repo:        gorilainvest/gorila-ui-components
  - provider:      npm
    skip_cleanup:  true
    email:         it@gorilainvest.com.br
    api_key:
      secure:      aMSe0CyVVQwOILizVyI04SaNvP7yu+rY0LrKH6YtSc0gS4/OB8Vj87ccAK6DKGyFUVXJEwvPcEy4ZCEfyIWs+A3uXr26fwcbp1po0TB0DfDJb7g2ik4dlBqZPxxrIbYASfewDpk5TPMudpCUYrTOyXjhT8owmMqQ4acCaAuSsnnUv5XTQvtKe2vP4gq45kq2oYDPG34WqCMKN3FPYF4xBNj7zD27j1MmAW5LxyTBN5SW9q+/Cr/s5I8Ls/0nh9MmHnx2LyY8Z2lw0viFIMpYbsTO6lXCG10Zrvkd33DkmHroYNIhiDZwQZPd+nZyz6H5EuKp1dQP5CJHMsKWJy+SR90Jt0RGFLQ3RzpFmliRmGNakZYe0X4+LMxe7fvY8AOF3Timwz5VjRLljvrKrh7Vl7QDuSMq6dACtrYl0HWvuWtw2mcAkyg4uJSemjwUUTQj1LD6L3TV8lgb4Jcrzn5160RcWt4/WBV6UcbSYnGxW6JmNumJzgmwZ9UHUF1VhpQ4Yu8oRkUZsH+kEaUeRfstovNEvQpW9IXZIbyyEGgbz7vhqC0kHCwa7ZxF1QGMLksrQtL3D7Xe9PAm2Cpif3fvERuMmU7ozgOUuGE+lKfRfidvJSy+uvJaUypTnP1ybj6gkN7IvdVJRhzNXNiD1/sV4hvaU+EcQ+XjVrAED60JRyc=
    on:
      tags:        true
      repo:        gorilainvest/gorila-ui-components
