language: node_js
node_js:
   - '9'
dist: trusty
sudo: required
branches:
only:
  - master
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli
script:
  - ng build --prod
  - npm test -- --code-coverage
  - npm run codacy-coverage
  - npm run ghpages

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/apps/widgets-system/
  fqdn: ui.gorilainvest.com.br
  keep-history: true
  on:
    branch: master
